name: build and push to docker hub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths-ignore:
      - README.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build UI
        run: |
          npm ci
          npm run build
          
      - name: log in to docker
        run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    
      - name: Get the tag for docker
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::8})
     
      - name: build and push
        run: |
          docker build . -t console:${{steps.vars.outputs.tag}}
          docker tag console:${{steps.vars.outputs.tag}} cloudworkstation/console:${{steps.vars.outputs.tag}}
          docker tag console:${{steps.vars.outputs.tag}} cloudworkstation/console:latest
          docker push cloudworkstation/console:${{steps.vars.outputs.tag}}
          docker push cloudworkstation/console:latest
